In [5]:
# creating numpy/n-d arrays
import numpy as np

In [6]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [7]:
type(arr1)

numpy.ndarray

In [13]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
type(arr4)

numpy.ndarray

In [20]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr7=np.linspace(5,10,4)   #এটি ১ থেকে ১০ পর্যন্ত এমন ৫টি সংখ্যা দেবে, যেগুলোর পার্থক্য সমান হবে।

  
arr7

array([ 5.        ,  6.66666667,  8.33333333, 10.        ])

In [23]:
arr8=arr7.copy()
arr8

array([ 5.        ,  6.66666667,  8.33333333, 10.        ])

In [24]:
arr1


array([1, 2, 3, 4, 5])

In [25]:
arr1.shape

(5,)

In [27]:
arr2.shape

(2, 3)

In [31]:
arr9=np.ones((3,3,2))
arr9

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [35]:
arr10=np.ones((5,4,2))
arr10

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [38]:
arra=np.ones((3,4,4))
arra

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [39]:
arra.ndim

3

In [1]:
arr1

NameError: name 'arr1' is not defined

In [41]:
arra.size

48

In [42]:
arra.itemsize

8

In [44]:
arr1.dtype


dtype('int32')

In [45]:
arra.dtype

dtype('float64')

In [4]:
import pandas as np

In [5]:
arr1.astype('float')



NameError: name 'arr1' is not defined

In [6]:
arr1

NameError: name 'arr1' is not defined