In [3]:
import numpy as np

In [5]:
arr=np.random.randint(low=0,high=100,size=20).reshape(4,5)
arr

array([[22, 78, 83, 80, 92],
       [97, 52,  0,  3, 50],
       [47, 37, 47, 81,  2],
       [83, 22, 59, 19, 32]])

In [8]:
arr[arr>50].reshape(3,3)    #indexing useing boolean arrays

array([[78, 83, 80],
       [92, 97, 52],
       [81, 83, 59]])

In [9]:
arr[(arr>50) & (arr%2!=0)]

array([83, 97, 81, 83, 59])

In [10]:
arr[(arr>50) & (arr%2!=0)]=0

In [11]:
arr

array([[22, 78,  0, 80, 92],
       [ 0, 52,  0,  3, 50],
       [47, 37, 47,  0,  2],
       [ 0, 22,  0, 19, 32]])

In [14]:
x=np.linspace(-40,40,100)
x.size

100

In [15]:
y=np.sin(x)
y.size

100

In [20]:
import matplotlib.pyplot as plt
%matplotlib inline

In [21]:
plt.plot(x,y)

In [22]:
y=x*x+2*x+6

In [24]:
plt.plot(x,y)