In [1]:
import numpy as np

In [3]:
np.random.random()

0.24435020123910556

In [7]:
np.random.seed(1)    #same random value
np.random.random()

0.417022004702574

In [12]:
np.random.uniform(3,10)

3.646370163381585

In [19]:
np.random.uniform(1,100,10).reshape(5,2)

array([[66.71566988, 51.97402209],
       [94.51488084, 59.06894901],
       [90.43678961, 14.60999571],
       [14.78835838, 80.93173758],
       [40.37000686, 17.37006551]])

In [28]:
np.random.randint(1,10,15).reshape(3,5)

array([[3, 2, 6, 5, 1],
       [8, 9, 6, 8, 1],
       [4, 2, 5, 5, 7]])

In [35]:
a=np.random.randint(1,10,6)
a

array([3, 1, 4, 6, 2, 3])

In [36]:
np.max(a)

6

In [38]:
np.argmax(a)


3

a[np.argmax(a)]


In [40]:
arr=([6,4,2,7,9,3])
arr

[6, 4, 2, 7, 9, 3]

In [43]:
a[a%2==1]=-1
a

array([-1, -1,  4,  6,  2, -1])

In [45]:
np.where(a%2==1,-1,a)

array([-1, -1,  4,  6,  2, -1])

In [47]:
a=np.sort(a)
a

array([-1, -1, -1,  2,  4,  6])

In [48]:
np.percentile(a,25)

-1.0

In [50]:
np.percentile(a,99.9)

5.990000000000002