In [2]:
import numpy as np

In [12]:
arr4=np.arange(6,12).reshape(3,2)
arr3=np.arange(6).reshape(2,3)
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
arr4.ndim

2

In [7]:
arr4.ravel()     #all dimention convert to 1d dimention

array([ 6,  7,  8,  9, 10, 11])

In [8]:
arr4.transpose()    #row to colimn and column to row

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [3]:
arr5=np.arange(12,18).reshape(2,3)
arr5
import numpy as np

NameError: name 'np' is not defined

In [5]:
np.hstack((arr3,arr5))

NameError: name 'arr3' is not defined

In [17]:
np.vstack((arr3,arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [18]:
np.hsplit(arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [19]:
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [20]:
arr8=np.arange(24).reshape(6,4)
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [4]:
import numpy as np